export class TTnv{
          id:string
          manhansu:string
          hodem:string
          ten:string
          ngaysinh:string
          gioitinh:string
          noisinh:string
          quequan:string
          diachithuongtru:string
          diachitamtru:string
          cmtnd_so:string
          cmtnd_ngayhethan:string
          cmtnd_noicap:string
          hochieu_so:string
          hochieu_ngaycap:string
          hochieu_ngayhethan:string
          ngayvaocongty:string
          phong_id:string
          ban_id:string
          congdoan_id:string
          chucvu_id:string
          nganhang_stk:string
          nganhang_id:string
          sosobaohiem:string
          honnhantinhtrang:string
          anhdaidien:string
          datnuoc_id:string
          thanhpho_id:string
          quanhuyen_id:string
          phuongxa:string
          tongiao_id:string
          suckhoetinhtrang:string
          dienthoai_nharieng:string
          dienthoai_didong:string
          email:string
          tinhtrangnhansu:string
          thutu:string
          chucvu:string
          capbac:string
}